### ISSUE TITLE
Tela About Us

### ISSUE THREAD

**Issue by mairacanal** [zenitheesc/Zenith-Monitor#10]
Essa tela conterá algumas informações sobre o Zenith e sobre o app.

**Comment by rubenszinho** [comment]
Primeira sugestão: https://www.figma.com/file/wqYC2TiwJplXDxuFdi7ZCm/Zenith-quem-somos?node-id=0%3A1

![Home Page - Mobile](https://user-images.githubusercontent.com/62901197/117751649-db52ce00-b1eb-11eb-81bc-5f3d23ffe4e3.jpg)
